force-app/main/default/objects/Fleet_Vehicle__c/Fleet_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Fleet Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fleet_Vehicle__c/fields/VIN__c.field-meta.xml
<CustomField>
    <fullName>VIN__c</fullName>
    <label>VIN</label>
    <length>17</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FleetTestDataFactory.cls
@isTest
public class FleetTestDataFactory {
    public static List<Fleet_Vehicle__c> createVehicles(Integer count) {
        List<Fleet_Vehicle__c> vehicles = new List<Fleet_Vehicle__c>();
        for(Integer i=0; i<count; i++) {
            vehicles.add(new Fleet_Vehicle__c(
                Name = 'Vehicle ' + i,
                VIN__c = 'VIN' + String.valueOf(i).leftPad(14, '0')
            ));
        }
        insert vehicles;
        return vehicles;
    }
}